const ASSETS=[
{type:"image",src:"assets/images/bg-sweet-day-interior.webp"},{type:"image",src:"assets/images/bg-moon-night-interior.webp"},{type:"image",src:"assets/images/logo-big.webp"},{type:"image",src:"assets/images/logo-nav-simple.webp"},{type:"image",src:"assets/images/hero-01.webp"},{type:"image",src:"assets/images/hero-02.webp"},{type:"image",src:"assets/images/hero-03.webp"},{type:"image",src:"assets/images/hero-04.webp"},{type:"video",src:"assets/videos/day-exterior-01.mp4"},{type:"video",src:"assets/videos/night-exterior-01.mp4"},{type:"audio",src:"assets/audio/lunix-theme.mp3"},{type:"audio",src:"assets/sfx/store-door-sfx.wav"}
];
const HEROES=[
{image:"assets/images/hero-01.webp",alt:"Maid catgirl holding LuniX Original Balance cat food",rarity:"Premium",name:"LOB Petfood",subtitle:"Daily Balance Formula",price:"Rp 89.000",description:"Nutrisi seimbang untuk mendukung energi, nafsu makan, dan rutinitas makan harian si kecil.",tags:["Premium","All Ages","Daily Care","Balanced Nutrition"],stats:[["Protein Support",92],["Fur Care",88],["Daily Energy",90],["Digestive Comfort",85],["Appetite Appeal",94]],benefits:[["🐾","Daily Balance","Cocok untuk rutinitas makan harian."],["✨","Soft Fur Care","Membantu mendukung bulu sehat."],["💜","Happy Appetite","Rasa yang dibuat menarik untuk si kecil."]]},
{image:"assets/images/hero-02.webp",alt:"Blonde catgirl holding LuniX Tuna Spark cat food",rarity:"Premium Gold",name:"LTS Petfood",subtitle:"Tuna Spark Formula",price:"Rp 99.000",description:"Varian tuna premium dengan aroma menggoda untuk kucing yang aktif, lahap, dan tampil anggun.",tags:["Premium Gold","Tuna Spark","Fur Care","Appetite Support"],stats:[["Appetite Appeal",94],["Protein Support",88],["Fur Care",90],["Daily Energy",84],["Omega Support",86]],benefits:[["🐟","Tuna First","Aroma tuna untuk daya tarik makan."],["👑","Premium Pick","Tampilan gold untuk rasa mewah."],["✨","Fur Glow","Membantu mendukung bulu lembut."]]},
{image:"assets/images/hero-03.webp",alt:"Sporty catgirl holding LuniX Active Boost cat food",rarity:"Energy",name:"LAB Petfood",subtitle:"Active Cat Formula",price:"Rp 94.000",description:"Untuk kucing yang suka bermain, berlari, dan eksplorasi, dengan fokus pada energi dan aktivitas harian.",tags:["Active Cat","Energy Boost","High Protein","Playful Support"],stats:[["Energy Boost",95],["Protein Support",90],["Muscle Support",88],["Digestive Comfort",82],["Daily Vitality",92]],benefits:[["⚡","Play Energy","Untuk companion yang aktif bergerak."],["💪","Muscle Support","Membantu mendukung tubuh aktif."],["🐈","Playful Mood","Cocok untuk rutinitas bermain."]]},
{image:"assets/images/hero-04.webp",alt:"Nurse healer catgirl holding LuniX Health Support cat food",rarity:"Care",name:"LHS Petfood",subtitle:"Health Support Formula",price:"Rp 99.000",description:"Formula daily care untuk mendukung wellness, kenyamanan, dan keseimbangan nutrisi si kecil.",tags:["Health Support","Daily Care","All Ages","Comfort Formula"],stats:[["Immune Support",90],["Digestive Comfort",88],["Daily Balance",86],["Fur & Skin Care",84],["Wellness Care",92]],benefits:[["💗","Wellness Care","Dukungan lembut untuk rutinitas sehat."],["🛡","Immune Support","Membantu mendukung daya tahan tubuh."],["🌸","Gentle Formula","Vibe soft care untuk daily feeding."]]}
];
const FLOORS=["welcome","showcase","support"];
let activeFloor="welcome",currentHero=0,isHeroChanging=false,isTransitioning=false,audioUnlocked=false;
const $=id=>document.getElementById(id);
const el={preloader:$("preloader"),fill:$("loadingFill"),percent:$("loadingPercent"),status:$("loadingStatus"),themeToggle:$("themeToggle"),themeIcon:$("themeIcon"),themeLabel:$("themeLabel"),dayVideo:$("dayVideo"),nightVideo:$("nightVideo"),heroFigure:$("heroFigure"),visualArea:$("visualArea"),heroImage:$("heroImage"),infoPanel:$("infoPanel"),heroNumber:$("heroNumber"),heroRarity:$("heroRarity"),productName:$("productName"),productSubtitle:$("productSubtitle"),productDescription:$("productDescription"),productPrice:$("productPrice"),tags:$("tags"),stats:$("stats"),benefits:$("benefits"),heroDots:$("heroDots"),ambientA:$("ambientBadgeA"),ambientB:$("ambientBadgeB"),prevHero:$("prevHero"),nextHero:$("nextHero"),detailButton:$("detailButton"),musicToggle:$("musicToggle"),musicIcon:$("musicIcon"),musicText:$("musicText"),bgm:$("bgm"),doorSfx:$("doorSfx")};
function loadAsset(asset){return new Promise(resolve=>{if(asset.type==="image"){const img=new Image();img.onload=img.onerror=resolve;img.src=asset.src;return}const media=document.createElement(asset.type);let done=false;const finish=()=>{if(done)return;done=true;resolve()};media.preload="auto";media.muted=asset.type==="video";media.playsInline=true;media.addEventListener("canplaythrough",finish,{once:true});media.addEventListener("loadeddata",finish,{once:true});media.addEventListener("error",finish,{once:true});media.src=asset.src;media.load();setTimeout(finish,7000)})}
async function runPreloader(){let done=0;updateLoad(0,"Preparing full asset preload...");const minimum=new Promise(r=>setTimeout(r,900));await Promise.all([minimum,Promise.all(ASSETS.map(async asset=>{await loadAsset(asset);done++;updateLoad(Math.round(done/ASSETS.length*100))}))]);updateLoad(100,"Ready.");startVideos();tryPlayBgm();setTimeout(()=>el.preloader.classList.add("is-hidden"),420)}
function updateLoad(n,msg){const messages=["Preparing full asset preload...","Loading images...","Buffering day video...","Buffering night video...","Loading audio and SFX...","Ready."];el.fill.style.width=n+"%";el.percent.textContent=n+"%";el.status.textContent=msg||messages[Math.min(messages.length-1,Math.floor(n/100*messages.length))]}
function startVideos(){[el.dayVideo,el.nightVideo].forEach(v=>{if(!v)return;v.muted=true;v.loop=true;v.playsInline=true;v.play().catch(()=>{})})}
function syncVideoTheme(){const night=document.body.classList.contains("theme-night");if(el.dayVideo&&el.nightVideo){if(Math.abs((el.dayVideo.currentTime||0)-(el.nightVideo.currentTime||0))>.4){const t=night?el.nightVideo.currentTime:el.dayVideo.currentTime;if(Number.isFinite(t)){el.dayVideo.currentTime=t;el.nightVideo.currentTime=t}}el.dayVideo.classList.toggle("is-showing",!night);el.nightVideo.classList.toggle("is-showing",night)}}
function setTheme(theme){const night=theme==="night";document.body.classList.toggle("theme-night",night);document.body.classList.toggle("theme-day",!night);el.themeIcon.textContent=night?"🌙":"☀";el.themeLabel.textContent=night?"Night":"Day";localStorage.setItem("lunix-theme",theme);syncVideoTheme()}
function initTheme(){setTheme(localStorage.getItem("lunix-theme")==="night"?"night":"day");el.themeToggle.addEventListener("click",()=>setTheme(document.body.classList.contains("theme-night")?"day":"night"))}
function renderHero(index,animate=true){const h=HEROES[index];if(animate){el.heroFigure.classList.add("is-changing");el.infoPanel.classList.add("is-changing")}setTimeout(()=>{el.heroImage.src=h.image;el.heroImage.alt=h.alt;el.heroNumber.textContent=`SHOWCASE ${String(index+1).padStart(2,"0")} / ${String(HEROES.length).padStart(2,"0")}`;el.heroRarity.textContent=h.rarity;el.productName.textContent=h.name;el.productSubtitle.textContent=h.subtitle;el.productDescription.textContent=h.description;el.productPrice.textContent=h.price;el.ambientA.textContent=h.tags.at(-1)||h.name;el.ambientB.textContent=h.benefits[1]?.[1]||h.subtitle;el.tags.innerHTML=h.tags.map(t=>`<span class="tag">${t}</span>`).join("");el.stats.innerHTML=h.stats.map(([name,val])=>`<div class="stat"><div class="stat__header"><span>${name}</span><span class="stat__value">${val}%</span></div><div class="stat__track"><span class="stat__fill" data-value="${val}"></span></div></div>`).join("");el.benefits.innerHTML=h.benefits.map(([icon,title,text])=>`<article class="benefit"><span class="benefit__icon">${icon}</span><h3>${title}</h3><p>${text}</p></article>`).join("");el.heroDots.innerHTML=HEROES.map((_,i)=>`<button class="hero-dot ${i===currentHero?"is-active":""}" type="button" data-index="${i}" aria-label="Show formula ${i+1}"></button>`).join("");el.heroDots.querySelectorAll(".hero-dot").forEach(dot=>dot.addEventListener("click",()=>setHero(Number(dot.dataset.index))));requestAnimationFrame(()=>document.querySelectorAll(".stat__fill").forEach((f,i)=>setTimeout(()=>f.style.width=f.dataset.value+"%",i*70)));if(animate){el.heroFigure.classList.remove("is-changing");el.infoPanel.classList.remove("is-changing")}isHeroChanging=false},animate?260:0)}
function setHero(index){if(isHeroChanging||index===currentHero)return;isHeroChanging=true;currentHero=(index+HEROES.length)%HEROES.length;renderHero(currentHero,true)}
function initCarousel(){renderHero(currentHero,false);el.nextHero.addEventListener("click",()=>setHero(currentHero+1));el.prevHero.addEventListener("click",()=>setHero(currentHero-1));el.detailButton.addEventListener("click",()=>alert(`${HEROES[currentHero].name}\n${HEROES[currentHero].subtitle}\n${HEROES[currentHero].price}`));document.addEventListener("keydown",e=>{if(activeFloor!=="showcase")return;if(e.key==="ArrowRight")setHero(currentHero+1);if(e.key==="ArrowLeft")setHero(currentHero-1)})}
function activateFloor(id,reveal=false){activeFloor=id;document.querySelectorAll(".floor").forEach(f=>{const on=f.dataset.floor===id;f.classList.toggle("is-active",on);f.classList.toggle("is-current",on);f.classList.remove("is-revealing")});document.querySelectorAll(".side-nav__item").forEach(a=>a.classList.toggle("is-active",a.dataset.go===id));history.replaceState(null,"","#"+id);if(reveal){const target=document.querySelector(`[data-floor="${id}"]`);requestAnimationFrame(()=>target.classList.add("is-revealing"));setTimeout(()=>target.classList.remove("is-revealing"),950)}}
function playDoor(){if(!el.doorSfx)return;el.doorSfx.currentTime=0;el.doorSfx.volume=.75;el.doorSfx.play().catch(()=>{})}
function goToFloor(target){if(isTransitioning||target===activeFloor||!FLOORS.includes(target))return;unlockAudio();const from=activeFloor,enter=from==="welcome"&&target==="showcase",exit=from==="showcase"&&target==="welcome";isTransitioning=true;if(enter||exit)playDoor();document.body.classList.add("cinema-cover",enter?"cinema-enter":exit?"cinema-exit":"cinema-normal");setTimeout(()=>activateFloor(target,true),enter||exit?1050:420);setTimeout(()=>document.body.classList.remove("cinema-cover"),enter||exit?1180:520);setTimeout(()=>{document.body.classList.remove("cinema-enter","cinema-exit","cinema-normal");isTransitioning=false},enter||exit?2050:950)}
function initFloorControls(){document.querySelectorAll("[data-go]").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();goToFloor(link.dataset.go)}));let lastWheel=0;window.addEventListener("wheel",e=>{if(window.matchMedia("(max-width:1060px)").matches)return;e.preventDefault();unlockAudio();if(isTransitioning)return;const now=Date.now();if(now-lastWheel<450)return;lastWheel=now;const i=FLOORS.indexOf(activeFloor);if(e.deltaY>25&&i<FLOORS.length-1)goToFloor(FLOORS[i+1]);if(e.deltaY<-25&&i>0)goToFloor(FLOORS[i-1])},{passive:false});document.addEventListener("keydown",e=>{if(isTransitioning)return;const i=FLOORS.indexOf(activeFloor);if(["PageDown","ArrowDown"," "].includes(e.key)&&i<FLOORS.length-1){e.preventDefault();goToFloor(FLOORS[i+1])}if(["PageUp","ArrowUp"].includes(e.key)&&i>0){e.preventDefault();goToFloor(FLOORS[i-1])}});const hash=location.hash.replace("#","");if(FLOORS.includes(hash))activateFloor(hash,false)}
function initParallax(){if(!window.matchMedia("(hover:hover) and (pointer:fine)").matches)return;el.visualArea.addEventListener("mousemove",e=>{if(isTransitioning)return;const r=el.visualArea.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.heroFigure.style.transform=`rotateY(${x*2.2}deg) rotateX(${-y*1.6}deg) translate3d(${x*6}px,${y*3}px,0)`});el.visualArea.addEventListener("mouseleave",()=>el.heroFigure.style.transform="")}
function tryPlayBgm(){if(!el.bgm)return;el.bgm.volume=.28;el.bgm.play().then(()=>{audioUnlocked=true;el.musicToggle.classList.add("is-playing");el.musicIcon.textContent="♫";el.musicText.textContent="On"}).catch(()=>{})}
function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;tryPlayBgm()}
function initAudio(){el.bgm.volume=.28;el.doorSfx.volume=.75;["pointerdown","keydown","wheel","touchstart"].forEach(evt=>document.addEventListener(evt,unlockAudio,{once:true,passive:true}));el.musicToggle.addEventListener("click",async()=>{if(el.bgm.paused){try{await el.bgm.play();audioUnlocked=true;el.musicToggle.classList.add("is-playing");el.musicIcon.textContent="♫";el.musicText.textContent="On"}catch{el.musicText.textContent="Tap"}}else{el.bgm.pause();el.musicToggle.classList.remove("is-playing");el.musicIcon.textContent="♪";el.musicText.textContent="Theme"}})}
document.addEventListener("DOMContentLoaded",()=>{initTheme();initCarousel();initFloorControls();initParallax();initAudio();runPreloader()});
